#!/usr/bin/env php
<?php
use Foundation\Console\ArgvInput;

require_once __DIR__ . '/autoload.php';
require_once __DIR__ . '../../../../wp-load.php';

use Foundation\Core\Application;
use Foundation\Console\Kernel;

$app = new Application(__DIR__);

/** @todo implement input interface */
$app->resolve(Kernel::class)->handle(new ArgvInput());

